---
include:
  - board: seeeduino_xiao_ble
    shield: xiao_dongle dongle_display
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: custom_22
    artifact-name: custom_22_left
  - board: seeeduino_xiao_ble
    shield: custom_22
    artifact-name: custom_22_right
    cmake-args: -DEXTRA_DTC_OVERLAY_FILE="../../config/custom_22_right.overlay"
  - board: efogtech_trackball_0
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: efogtech_trackball_0
    shield: settings_reset
