---
include:
  - board: seeeduino_xiao_ble
    shield: xiao_dongle dongle_display
  - board: seeeduino_xiao_ble
    shield: custom_22
    artifact-name: custom_22_left
  - board: seeeduino_xiao_ble
    shield: custom_22
    artifact-name: custom_22_right
  - board: efogtech_trackball_0
  - board: seeeduino_xiao_ble
    shield: settings_reset
