manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: butonche
      url-base: https://github.com/butonche
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-feature-rolling-combos
      remote: butonche
      revision: main
  self:
    path: config
