manifest:
  remotes:
    - name: vvv-ca
      url-base: https://github.com/vvv-ca
  projects:
    - name: zmk
      remote: vvv-ca
      revision: combo-rolling
      import: app/west.yml
  self:
    path: config
