CONFIG_ZMK_KEYBOARD_NAME="Custom 22"
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=3
CONFIG_BT_MAX_PAIRED=4
CONFIG_BT_MAX_CONN=4
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y
CONFIG_ZMK_POINTING=y

# Disable trackball-specific efogdev modules (auto-enable under ZMK_POINTING)
CONFIG_ZMK_POINTER_2S_MIXER=n
CONFIG_ZMK_AXIS_CLAMPER=n
CONFIG_ZMK_ACCEL_CURVE=n
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=n
CONFIG_ZMK_INPUT_PROCESSOR_ROTATE_PLANE=n
CONFIG_ZMK_RUNTIME_CONFIG=n
